# New ports collection makefile for:	webkit-qt4
# Date created:		2007-10-22
# Whom:			Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom$

PKGNAMESUFFIX=	-qt4

MASTERDIR=	${.CURDIR}/../../www/webkit

WEBKIT_SLAVE=	qt4
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
