# Created by: Joe Marcus Clarke <marcus@FreeBSD.org>
# $FreeBSD$
#    $MCom$

PORTNAME=	gnome-common
PORTVERSION=	3.12.0
CATEGORIES=	devel
MASTER_SITES=	GNOME
DIST_SUBDIR=	gnome2

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	Common automake macros for GNOME 2 and GNOME 3

USES=		gmake pkgconfig tar:xz
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
